# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-01 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=3)),
                ('dt', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
